@extends('layouts.app')
@section('title', 'Comment Jet | Price')
@section('content')

    <section class="container mx-auto mt-10 lg:mt-16">
        <h1 class="text-center text-[30px] lg:text-[64px] leading-[44px] lg:leading-[82px] font-medium">Community workshop:
            Automatically create and send PDF reports from
            type form responses
        </h1>
        <p class="text-[18px] leading-8 py-5 text-center">January 30 2024 by Mary</p>
        <div class=" text-center">

            <button type="button"
                class="bg-[#000000] text-white  font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center me-2">
                <img src="{{asset('img/facebookwhite.png')}}" class="w-4 h-4" alt="">
            </button>

            <button type="button"
                class="bg-[#000000] text-white  font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center me-2">
                <svg class=" text-white" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                  </svg>
            </button>
            <button type="button"
                class="bg-[#000000] text-white  font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center me-2">
                <svg class="text-white" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334q.002-.211-.006-.422A6.7 6.7 0 0 0 16 3.542a6.7 6.7 0 0 1-1.889.518 3.3 3.3 0 0 0 1.447-1.817 6.5 6.5 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.32 9.32 0 0 1-6.767-3.429 3.29 3.29 0 0 0 1.018 4.382A3.3 3.3 0 0 1 .64 6.575v.045a3.29 3.29 0 0 0 2.632 3.218 3.2 3.2 0 0 1-.865.115 3 3 0 0 1-.614-.057 3.28 3.28 0 0 0 3.067 2.277A6.6 6.6 0 0 1 .78 13.58a6 6 0 0 1-.78-.045A9.34 9.34 0 0 0 5.026 15"/>
                  </svg>
            </button>
        </div>
    </section>

<section class="container mx-auto my-10">
    <img src="{{asset('img/blog/shearfeedback.png')}}" class="w-full lg:w-full h-[163px] lg:h-[614px]" alt="">
    <div class="lg:px-[150px]">
        <div class="py-8">
            <p class="text-[18px] lg:text-[22px] leading-6 lg:leading-9">You have the power to copy the link generated by our platform for quick access, or chart your own unique project, inviting clients and members to set sail alongside you on this exciting journey of teamwork and achievement.</p>
            <p class="text-[18px] lg:text-[22px] leading-6 lg:leading-9 py-5">It’s 3 p.m. on a Friday.</p>
            <p class="text-[18px] lg:text-[22px] leading-6 lg:leading-9 py-5">You’re buzzing with anticipation because the project you’ve poured your heart into is on the brink of completion. You’re picturing a tranquil weekend, free from stress, just a few approval clicks away.</p>
            <img src="{{asset('img/blog/feedback2.png')}}" class="px-4 lg:w-full lg:h-[614px] py-8" alt="">
            <div>
                <p class="text-[18px] lg:text-[22px] leading-6 lg:leading-9 pb-3">“Ugh, not this again,” you sigh.</p>
                <p class="text-[18px] lg:text-[22px] leading-6 lg:leading-9 py-3">But, hold on! What if there was a magical solution that could streamline the approval process, saving you from the chaos and the pounding headache? </p>
                <p class="text-[18px] lg:text-[22px] leading-6 lg:leading-9 py-3">Meet your knight in shining armor, workflow approval software. It’s here to liberate you from the infinite loop of approval hell.</p>
                <p class="text-[18px] lg:text-[22px] leading-6 lg:leading-9 py-3">Say adios to the exhausting chase for approvals and hello to a streamlined process that makes room for the work you truly enjoy. </p>
                <P class="text-[18px] lg:text-[22px] leading-6 lg:leading-9 pt-3">So, creative geniuses, let’s take you on a journey through the wonderful world of workflow approval software.</P>
            </div>
        </div>
    </div>
</section>


    <x-section-start-use />

@endsection
